"""empty message

Revision ID: 938623c46f7f
Revises: cc68005eed46
Create Date: 2022-12-10 14:27:50.997171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '938623c46f7f'
down_revision = 'cc68005eed46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
